### PR TITLE
Fix/add security headers

### PR DESCRIPTION
**Pull request by dreamorosi**
*Issue #, if available:*
#131 

*Description of changes:*
Added a CloudFront Function to the CloudFront Distribution to process responses after when they leave the edge location and before they arrive to the client.

The function runs and adds several headers to the response, full details & implementation [here](https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/example-function-add-security-headers.html).

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by dreamorosi** [comment]
Infra resources work as intended but one of the rules is too restrictive and blocks all remote css/js files so the Web UI becomes unusable, this is the rule that needs proper configuration:
```js
headers['content-security-policy'] = { value: "default-src 'none'; img-src 'self'; script-src 'self'; style-src 'self'; object-src 'none'"}; 
```

MDN Documentation [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy).

**Comment by dreamorosi** [comment]
Found a configuration that works and gives great score:
```js
headers['content-security-policy'] = { value: "default-src 'none'; img-src 'self' https://${DISTRIBUTION_ID}.cloudfront.net; script-src 'self' https://${DISTRIBUTION_ID}.cloudfront.net; style-src 'self' https://${DISTRIBUTION_ID}.cloudfront.net; connect-src 'self' https://${DISTRIBUTION_ID}.cloudfront.net https://${API_GW_ID}.execute-api.${REGION}.amazonaws.com https://cognito-identity.${REGION}.amazonaws.com; frame-ancestors 'none'; base-uri 'none'; form-action 'none'"}; 
```

Details of most important ones:
* `frame-ancestors` helps with clickjacking
* `connect-src` defines where the WebUI can connect to, in our case we need the Cf Distribution to get static assets, API, and Cognito
* `default-src` is the catch-all rule that denies by default all outgoing requests from the WebUI.

This works but will have to create a custom resource to deploy the CloudFront Function after everything else has already been deployed and place these values in the string.

**Comment by brandold** [comment]
Hey @dreamorosi, given this is a low risk item, I wouldn't spend too much time if we can't come up with a simple way to address it.

**Comment by dreamorosi** [comment]
Was able to implement the CloudFront Function with a combination of security headers that allows the website to work. I had to implement a custom resource to associate the CF Function to the CF Distribution to avoid a circular dependency.

**Pull request closed without merging**
